config/routes.rb
Rails.application.routes.draw do
  resources :labels, only: [:show]

  resources :topics do 
    resources :posts, except: [:index]
  end 

  resources :posts, only: [] do#[] to create posts/:post_id/comments
    resources :comments, only: [:create, :destroy] #no need for show update or edit because comments will be shown on the posts#show
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end 

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  namespace :api do 
    namespace :v1 do 
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new]
    end 
  end 
end 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RateIt</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
          <%= image_tag User.avatar_url(current_user, 48), class: "gravatar" %>
            <div class="pull-left">
              <%= link_to current_user.name, user_path(current_user) %> <br/> <%= link_to "Sign Out", session_path(current_user), method: :delete %>
            </div>
          <% else %>
            <%= link_to "Sign In", new_session_path %> or 
            <%= link_to "Sign Up", new_user_path %>
        <% end %>
      </div>
    </ul>

    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>


<%= yield %>
</div>

</body>
</html>